// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: tours_service.proto

package tours

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tour_GetAvailableEquipment_FullMethodName = "/Tour/GetAvailableEquipment"
	Tour_GetAllEquipment_FullMethodName       = "/Tour/GetAllEquipment"
	Tour_GetEquipment_FullMethodName          = "/Tour/GetEquipment"
	Tour_CreateEquipment_FullMethodName       = "/Tour/CreateEquipment"
	Tour_UpdateEquipment_FullMethodName       = "/Tour/UpdateEquipment"
	Tour_DeleteEquipment_FullMethodName       = "/Tour/DeleteEquipment"
	Tour_GetAllTour_FullMethodName            = "/Tour/GetAllTour"
	Tour_GetTour_FullMethodName               = "/Tour/GetTour"
	Tour_CreateTour_FullMethodName            = "/Tour/CreateTour"
	Tour_UpdateTour_FullMethodName            = "/Tour/UpdateTour"
	Tour_DeleteTour_FullMethodName            = "/Tour/DeleteTour"
	Tour_GetTourByAuthorId_FullMethodName     = "/Tour/GetTourByAuthorId"
	Tour_AddTourEquipment_FullMethodName      = "/Tour/AddTourEquipment"
	Tour_DeleteTourEquipment_FullMethodName   = "/Tour/DeleteTourEquipment"
)

// TourClient is the client API for Tour service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourClient interface {
	// Equipment
	GetAvailableEquipment(ctx context.Context, in *EquipmentIds, opts ...grpc.CallOption) (*EquipmentsResponse, error)
	GetAllEquipment(ctx context.Context, in *Page, opts ...grpc.CallOption) (*PagedEquipmentsResponse, error)
	GetEquipment(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EquipmentResponse, error)
	CreateEquipment(ctx context.Context, in *EquipmentResponse, opts ...grpc.CallOption) (*EquipmentResponse, error)
	UpdateEquipment(ctx context.Context, in *UpdateEquipmentId, opts ...grpc.CallOption) (*EquipmentResponse, error)
	DeleteEquipment(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Blank, error)
	// Tour
	GetAllTour(ctx context.Context, in *Page, opts ...grpc.CallOption) (*PagedToursResponse, error)
	GetTour(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TourResponse, error)
	CreateTour(ctx context.Context, in *TourResponse, opts ...grpc.CallOption) (*TourResponse, error)
	UpdateTour(ctx context.Context, in *UpdateTourId, opts ...grpc.CallOption) (*TourResponse, error)
	DeleteTour(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Blank, error)
	GetTourByAuthorId(ctx context.Context, in *TourByAuthorId, opts ...grpc.CallOption) (*ToursResponse, error)
	AddTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*Blank, error)
	DeleteTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*Blank, error)
}

type tourClient struct {
	cc grpc.ClientConnInterface
}

func NewTourClient(cc grpc.ClientConnInterface) TourClient {
	return &tourClient{cc}
}

func (c *tourClient) GetAvailableEquipment(ctx context.Context, in *EquipmentIds, opts ...grpc.CallOption) (*EquipmentsResponse, error) {
	out := new(EquipmentsResponse)
	err := c.cc.Invoke(ctx, Tour_GetAvailableEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) GetAllEquipment(ctx context.Context, in *Page, opts ...grpc.CallOption) (*PagedEquipmentsResponse, error) {
	out := new(PagedEquipmentsResponse)
	err := c.cc.Invoke(ctx, Tour_GetAllEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) GetEquipment(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EquipmentResponse, error) {
	out := new(EquipmentResponse)
	err := c.cc.Invoke(ctx, Tour_GetEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) CreateEquipment(ctx context.Context, in *EquipmentResponse, opts ...grpc.CallOption) (*EquipmentResponse, error) {
	out := new(EquipmentResponse)
	err := c.cc.Invoke(ctx, Tour_CreateEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) UpdateEquipment(ctx context.Context, in *UpdateEquipmentId, opts ...grpc.CallOption) (*EquipmentResponse, error) {
	out := new(EquipmentResponse)
	err := c.cc.Invoke(ctx, Tour_UpdateEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) DeleteEquipment(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Blank, error) {
	out := new(Blank)
	err := c.cc.Invoke(ctx, Tour_DeleteEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) GetAllTour(ctx context.Context, in *Page, opts ...grpc.CallOption) (*PagedToursResponse, error) {
	out := new(PagedToursResponse)
	err := c.cc.Invoke(ctx, Tour_GetAllTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) GetTour(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TourResponse, error) {
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, Tour_GetTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) CreateTour(ctx context.Context, in *TourResponse, opts ...grpc.CallOption) (*TourResponse, error) {
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, Tour_CreateTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) UpdateTour(ctx context.Context, in *UpdateTourId, opts ...grpc.CallOption) (*TourResponse, error) {
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, Tour_UpdateTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) DeleteTour(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Blank, error) {
	out := new(Blank)
	err := c.cc.Invoke(ctx, Tour_DeleteTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) GetTourByAuthorId(ctx context.Context, in *TourByAuthorId, opts ...grpc.CallOption) (*ToursResponse, error) {
	out := new(ToursResponse)
	err := c.cc.Invoke(ctx, Tour_GetTourByAuthorId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) AddTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*Blank, error) {
	out := new(Blank)
	err := c.cc.Invoke(ctx, Tour_AddTourEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) DeleteTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*Blank, error) {
	out := new(Blank)
	err := c.cc.Invoke(ctx, Tour_DeleteTourEquipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServer is the server API for Tour service.
// All implementations must embed UnimplementedTourServer
// for forward compatibility
type TourServer interface {
	// Equipment
	GetAvailableEquipment(context.Context, *EquipmentIds) (*EquipmentsResponse, error)
	GetAllEquipment(context.Context, *Page) (*PagedEquipmentsResponse, error)
	GetEquipment(context.Context, *Id) (*EquipmentResponse, error)
	CreateEquipment(context.Context, *EquipmentResponse) (*EquipmentResponse, error)
	UpdateEquipment(context.Context, *UpdateEquipmentId) (*EquipmentResponse, error)
	DeleteEquipment(context.Context, *Id) (*Blank, error)
	// Tour
	GetAllTour(context.Context, *Page) (*PagedToursResponse, error)
	GetTour(context.Context, *Id) (*TourResponse, error)
	CreateTour(context.Context, *TourResponse) (*TourResponse, error)
	UpdateTour(context.Context, *UpdateTourId) (*TourResponse, error)
	DeleteTour(context.Context, *Id) (*Blank, error)
	GetTourByAuthorId(context.Context, *TourByAuthorId) (*ToursResponse, error)
	AddTourEquipment(context.Context, *TourEquipment) (*Blank, error)
	DeleteTourEquipment(context.Context, *TourEquipment) (*Blank, error)
	mustEmbedUnimplementedTourServer()
}

// UnimplementedTourServer must be embedded to have forward compatible implementations.
type UnimplementedTourServer struct {
}

func (UnimplementedTourServer) GetAvailableEquipment(context.Context, *EquipmentIds) (*EquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableEquipment not implemented")
}
func (UnimplementedTourServer) GetAllEquipment(context.Context, *Page) (*PagedEquipmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEquipment not implemented")
}
func (UnimplementedTourServer) GetEquipment(context.Context, *Id) (*EquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEquipment not implemented")
}
func (UnimplementedTourServer) CreateEquipment(context.Context, *EquipmentResponse) (*EquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEquipment not implemented")
}
func (UnimplementedTourServer) UpdateEquipment(context.Context, *UpdateEquipmentId) (*EquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEquipment not implemented")
}
func (UnimplementedTourServer) DeleteEquipment(context.Context, *Id) (*Blank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEquipment not implemented")
}
func (UnimplementedTourServer) GetAllTour(context.Context, *Page) (*PagedToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTour not implemented")
}
func (UnimplementedTourServer) GetTour(context.Context, *Id) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTour not implemented")
}
func (UnimplementedTourServer) CreateTour(context.Context, *TourResponse) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourServer) UpdateTour(context.Context, *UpdateTourId) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTour not implemented")
}
func (UnimplementedTourServer) DeleteTour(context.Context, *Id) (*Blank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTour not implemented")
}
func (UnimplementedTourServer) GetTourByAuthorId(context.Context, *TourByAuthorId) (*ToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourByAuthorId not implemented")
}
func (UnimplementedTourServer) AddTourEquipment(context.Context, *TourEquipment) (*Blank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTourEquipment not implemented")
}
func (UnimplementedTourServer) DeleteTourEquipment(context.Context, *TourEquipment) (*Blank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTourEquipment not implemented")
}
func (UnimplementedTourServer) mustEmbedUnimplementedTourServer() {}

// UnsafeTourServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServer will
// result in compilation errors.
type UnsafeTourServer interface {
	mustEmbedUnimplementedTourServer()
}

func RegisterTourServer(s grpc.ServiceRegistrar, srv TourServer) {
	s.RegisterService(&Tour_ServiceDesc, srv)
}

func _Tour_GetAvailableEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipmentIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetAvailableEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetAvailableEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetAvailableEquipment(ctx, req.(*EquipmentIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_GetAllEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetAllEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetAllEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetAllEquipment(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_GetEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetEquipment(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_CreateEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipmentResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).CreateEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_CreateEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).CreateEquipment(ctx, req.(*EquipmentResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_UpdateEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEquipmentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).UpdateEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_UpdateEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).UpdateEquipment(ctx, req.(*UpdateEquipmentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_DeleteEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).DeleteEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_DeleteEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).DeleteEquipment(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_GetAllTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetAllTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetAllTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetAllTour(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_GetTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetTour(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).CreateTour(ctx, req.(*TourResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_UpdateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).UpdateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_UpdateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).UpdateTour(ctx, req.(*UpdateTourId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_DeleteTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).DeleteTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_DeleteTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).DeleteTour(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_GetTourByAuthorId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourByAuthorId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetTourByAuthorId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetTourByAuthorId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetTourByAuthorId(ctx, req.(*TourByAuthorId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_AddTourEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourEquipment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).AddTourEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_AddTourEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).AddTourEquipment(ctx, req.(*TourEquipment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_DeleteTourEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourEquipment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).DeleteTourEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_DeleteTourEquipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).DeleteTourEquipment(ctx, req.(*TourEquipment))
	}
	return interceptor(ctx, in, info, handler)
}

// Tour_ServiceDesc is the grpc.ServiceDesc for Tour service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tour_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tour",
	HandlerType: (*TourServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableEquipment",
			Handler:    _Tour_GetAvailableEquipment_Handler,
		},
		{
			MethodName: "GetAllEquipment",
			Handler:    _Tour_GetAllEquipment_Handler,
		},
		{
			MethodName: "GetEquipment",
			Handler:    _Tour_GetEquipment_Handler,
		},
		{
			MethodName: "CreateEquipment",
			Handler:    _Tour_CreateEquipment_Handler,
		},
		{
			MethodName: "UpdateEquipment",
			Handler:    _Tour_UpdateEquipment_Handler,
		},
		{
			MethodName: "DeleteEquipment",
			Handler:    _Tour_DeleteEquipment_Handler,
		},
		{
			MethodName: "GetAllTour",
			Handler:    _Tour_GetAllTour_Handler,
		},
		{
			MethodName: "GetTour",
			Handler:    _Tour_GetTour_Handler,
		},
		{
			MethodName: "CreateTour",
			Handler:    _Tour_CreateTour_Handler,
		},
		{
			MethodName: "UpdateTour",
			Handler:    _Tour_UpdateTour_Handler,
		},
		{
			MethodName: "DeleteTour",
			Handler:    _Tour_DeleteTour_Handler,
		},
		{
			MethodName: "GetTourByAuthorId",
			Handler:    _Tour_GetTourByAuthorId_Handler,
		},
		{
			MethodName: "AddTourEquipment",
			Handler:    _Tour_AddTourEquipment_Handler,
		},
		{
			MethodName: "DeleteTourEquipment",
			Handler:    _Tour_DeleteTourEquipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours_service.proto",
}
